name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: ./
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 897f0af131b854b3c4ad82cb0a144c0f
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIMEZONE: Asia/Shanghai
